# Generated by Django 5.0.6 on 2024-06-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo_author',
            field=models.FileField(blank=True, null=True, upload_to='bookfile'),
        ),
    ]
